//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MazeSolving.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MazeSolving.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string _7 {
            get {
                return ResourceManager.GetString("7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Searching Algorithm.
        /// </summary>
        internal static string Form1_button__Click_Select_Searching_Algorithm {
            get {
                return ResourceManager.GetString("Form1_button__Click_Select_Searching_Algorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set EndPoint..
        /// </summary>
        internal static string Form1_button__Click_Set_EndPoint_ {
            get {
                return ResourceManager.GetString("Form1_button__Click_Set_EndPoint_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Maze Size.
        /// </summary>
        internal static string Form1_button4_Click_Select_Maze_Size {
            get {
                return ResourceManager.GetString("Form1_button4_Click_Select_Maze_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Maze....
        /// </summary>
        internal static string Form1_button5_Click_Creating_Maze___ {
            get {
                return ResourceManager.GetString("Form1_button5_Click_Creating_Maze___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        internal static string Form1_button5_Click_Done_ {
            get {
                return ResourceManager.GetString("Form1_button5_Click_Done_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause!.
        /// </summary>
        internal static string Form1_button8_Click_Pause_ {
            get {
                return ResourceManager.GetString("Form1_button8_Click_Pause_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        internal static string Form1_button9_Click_OFF {
            get {
                return ResourceManager.GetString("Form1_button9_Click_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        internal static string Form1_button9_Click_ON {
            get {
                return ResourceManager.GetString("Form1_button9_Click_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Start Point..
        /// </summary>
        internal static string Form1_button9_Click_Set_Start_Point_ {
            get {
                return ResourceManager.GetString("Form1_button9_Click_Set_Start_Point_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No solution available!.
        /// </summary>
        internal static string Form1_IfDfs_No_solution_available_ {
            get {
                return ResourceManager.GetString("Form1_IfDfs_No_solution_available_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At this speed the result may not be accurate.
        /// </summary>
        internal static string Form1_timer2_Tick_At_this_speed_the_result_may_not_be_accurate {
            get {
                return ResourceManager.GetString("Form1_timer2_Tick_At_this_speed_the_result_may_not_be_accurate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solving ! .
        /// </summary>
        internal static string Form1_timer2_Tick_Solving___ {
            get {
                return ResourceManager.GetString("Form1_timer2_Tick_Solving___", resourceCulture);
            }
        }
    }
}
